[package]
name = "bevy_descendant_collector_derive"
description = "Derive macro for bevy_descendant_collector"
license = "MIT"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
bevy = { version = "0.13" }
proc-macro2 = { version = "1.0.78" }
quote = { version = "1.0.35" }
syn = { version = "2.0.48" }
