[package]
name = "bevy_descendant_collector_derive"
description = "Derive macro for bevy_descendant_collector"
version = "0.1.0"
edition = "2021"

homepage.workspace = true
repository.workspace = true
documentation.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
bevy = { version = "0.13" }
proc-macro2 = { version = "1.0.79" }
quote = { version = "1.0.35" }
syn = { version = "2.0.53" }
